/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import CohLean.Cohomology.EulerCharacteristic.Additivity
import CohLean.Numerical.GrothendieckGroup.Lattice

/-!
# Additive invariants on the coherent Grothendieck group

This is the dimension-independent descent layer used by geometric Riemann--Roch.  An invariant
of coherent sheaves which is invariant under isomorphism and additive in short exact sequences
factors through the explicit presentation of `K₀(Coh X)`.
-/

universe u v

open CategoryTheory

namespace CohLean.RiemannRoch

open AlgebraicGeometry
open AlgebraicGeometry.Cohomology

variable {k : Type u} [Field k]
variable {X : Variety k}

noncomputable section

/-- An invariant of coherent sheaves which is invariant under isomorphism and additive in
short exact sequences. -/
structure CoherentAdditiveInvariant (X : Variety k) (M : Type v) [AddCommGroup M] where
  obj : Coh X.toScheme → M
  map_iso : ∀ {F G : Coh X.toScheme}, (F ≅ G) → obj F = obj G
  map_shortExact : ∀ (S : ShortComplex (Coh X.toScheme)), S.ShortExact →
    obj S.X₂ = obj S.X₁ + obj S.X₃

namespace CoherentAdditiveInvariant

variable {M : Type v} [AddCommGroup M]

/-- The additive homomorphism from the free abelian group generated by coherent sheaves. -/
noncomputable def freeHom (I : CoherentAdditiveInvariant X M) :
    FreeAbelianGroup (Coh X.toScheme) →+ M :=
  FreeAbelianGroup.lift I.obj

/-- Every defining coherent-Grothendieck relation is killed by an additive invariant. -/
theorem coherentGrothendieckRelations_le_ker (I : CoherentAdditiveInvariant X M) :
    coherentGrothendieckRelations X ≤ I.freeHom.ker := by
  rw [coherentGrothendieckRelations, AddSubgroup.closure_le]
  intro z hz
  change I.freeHom z = 0
  cases hz with
  | iso e =>
      simp only [freeHom, map_sub, FreeAbelianGroup.lift_apply_of]
      rw [I.map_iso e, sub_self]
  | shortExact S hS =>
      simp only [freeHom, map_sub, FreeAbelianGroup.lift_apply_of]
      rw [I.map_shortExact S hS]
      abel

/-- The homomorphism on `K₀(Coh X)` determined by an additive invariant. -/
noncomputable def grothendieckHom (I : CoherentAdditiveInvariant X M) :
    CoherentGrothendieckGroup X →+ M :=
  QuotientAddGroup.lift (coherentGrothendieckRelations X) I.freeHom
    I.coherentGrothendieckRelations_le_ker

@[simp]
theorem grothendieckHom_class (I : CoherentAdditiveInvariant X M)
    (F : Coh X.toScheme) :
    I.grothendieckHom (coherentGrothendieckClass F) = I.obj F := by
  simp [grothendieckHom, coherentGrothendieckClass, freeHom]

end CoherentAdditiveInvariant

/-- Two additive homomorphisms out of `K₀(Coh X)` agree when they agree on coherent-sheaf
classes. -/
theorem coherentGrothendieckGroup_hom_ext {M : Type v} [AddCommGroup M]
    {f g : CoherentGrothendieckGroup X →+ M}
    (h : ∀ F : Coh X.toScheme,
      f (coherentGrothendieckClass F) = g (coherentGrothendieckClass F)) :
    f = g := by
  apply AddMonoidHom.ext
  intro q
  obtain ⟨z, rfl⟩ := QuotientAddGroup.mk'_surjective
    (coherentGrothendieckRelations X) q
  induction z using FreeAbelianGroup.induction_on with
  | zero => simp
  | of F => simpa [coherentGrothendieckClass] using h F
  | neg F hF => simpa using congrArg Neg.neg hF
  | add x y hx hy => simpa [map_add] using congrArg₂ (· + ·) hx hy

end

end CohLean.RiemannRoch
