/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.CompactlyGenerated
import DerivedAlgGeo.CategoryTheory.Triangulated.TStructure.Aisle

/-!
# The compact-generator t-structure constructor

This file formalizes the final assembly in Theorem A.13 of
arXiv:2607.28411v1.  A shift-stable family of generators makes `Coprod(G)`
shift-stable.  Once Brown representability supplies an approximation triangle
with left term in `Coprod(G)` and right term in its right orthogonal, the aisle
constructor produces the compactly generated t-structure and formula (A.2).

The structure `CompactGeneratorApproximation` contains those approximation
triangles, while `ofApproximationMaps` constructs them from Brown-style
universal maps and proves the required orthogonality. No instance is
manufactured merely from compactness: existence of the universal maps is the
Brown-representability step that remains to be formalized.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open CategoryTheory.Triangulated

universe w v u

namespace CategoryTheory

namespace ObjectProperty

variable {C : Type u} [Category.{v} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C]
  {G : ObjectProperty C}

/-- If the generators are closed under `[1]`, so is their coproduct-and-extension
closure.  This is Remark A.12(1) propagated through `Coprod`. -/
theorem coprodClosure_le_shift
    (hG : G ≤ G.shift (1 : ℤ)) :
    G.coprodClosure.{w} ≤ G.coprodClosure.{w}.shift (1 : ℤ) := by
  intro X hX
  induction hX with
  | of_mem X hX =>
      exact G.le_coprodClosure.{w} _ (hG X hX)
  | of_iso e _ ih =>
      exact .of_iso ((shiftFunctor C (1 : ℤ)).mapIso e) ih
  | @of_coproduct ι F c hc hF ih =>
      letI : PreservesColimitsOfShape (Discrete ι) (shiftFunctor C (1 : ℤ)) :=
        inferInstance
      exact .of_coproduct ((shiftFunctor C (1 : ℤ)).mapCocone c)
        (isColimitOfPreserves (shiftFunctor C (1 : ℤ)) hc) ih
  | of_extension T hT _ _ ih₁ ih₃ =>
      exact .of_extension ((Triangle.shiftFunctor C (1 : ℤ)).obj T)
        (Triangle.shift_distinguished T hT (1 : ℤ)) ih₁ ih₃

end ObjectProperty

namespace Triangulated.TStructure

variable {C : Type u} [Category.{v} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C]
  {G : ObjectProperty C}

/-- The approximation output needed in the Brown-representability step of
Theorem A.13. -/
structure CompactGeneratorApproximation (G : ObjectProperty C) : Prop where
  /-- The chosen generating family satisfies `G[1] ⊆ G`, in object-property
  form. -/
  generator_shift : G ≤ G.shift (1 : ℤ)
  /-- Every object admits the approximation triangle constructed by Brown
  representability. -/
  exists_triangle (A : C) :
    ∃ (X Y : C) (_ : G.coprodClosure.{w} X)
      (_ : G.coprodClosure.{w}.rightOrthogonal Y)
      (f : X ⟶ A) (g : A ⟶ Y) (h : Y ⟶ X⟦(1 : ℤ)⟧),
        Triangle.mk f g h ∈ distTriang C

namespace CompactGeneratorApproximation

/-- Brown-style universal maps produce the approximation triangles required
by Theorem A.13.

The cone and its right-orthogonality are constructed internally by
`AisleData.ofApproximationMaps`; callers only provide the generator shift and
the two Hom controls on the universal maps. -/
theorem ofApproximationMaps
    (hG : G ≤ G.shift (1 : ℤ))
    (happrox : ∀ A : C,
      Nonempty (ApproximationMap G.coprodClosure.{w} A)) :
    CompactGeneratorApproximation.{w} G := by
  have hAisle : AisleData G.coprodClosure.{w} :=
    AisleData.ofApproximationMaps
      (ObjectProperty.coprodClosure_le_shift hG) happrox
  exact
    { generator_shift := hG
      exists_triangle := hAisle.exists_triangle }

variable (h : CompactGeneratorApproximation.{w} G)
include h

/-- The approximation data make `Coprod(G)` an aisle. -/
theorem aisleData : AisleData G.coprodClosure.{w} where
  shift := ObjectProperty.coprodClosure_le_shift h.generator_shift
  exists_triangle := h.exists_triangle

/-- The t-structure assembled from the Brown-representability approximation
triangles. -/
noncomputable def tStructure : TStructure C := h.aisleData.tStructure

@[simp]
lemma tStructure_le_zero : h.tStructure.le 0 = G.coprodClosure.{w} := by
  simp [tStructure]

/-- Formula (A.2): the degree-one coaisle is the right orthogonal of
`Coprod(G)`. -/
@[simp]
lemma tStructure_ge_one :
    h.tStructure.ge 1 = G.coprodClosure.{w}.rightOrthogonal := by
  simp [tStructure]

/-- The assembled t-structure is compactly generated by `G` once compactness
of the generators is supplied. -/
theorem isCompactlyGeneratedBy
    (hcompact : G ≤ ObjectProperty.compactObjects.{w} (C := C)) :
    h.tStructure.IsCompactlyGeneratedBy.{w} G where
  compact := hcompact
  le_zero_eq := h.tStructure_le_zero

end CompactGeneratorApproximation

end Triangulated.TStructure

end CategoryTheory
