/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.CompactlyGenerated.IndExtension

/-!
# The categorical core of Polishchuk's inducing theorem

This file assembles Steps 1--4 of Theorem A.17 in arXiv:2607.28411v1 after
the compactly generated large t-structures have been constructed.

The result constructs a bounded t-structure on the selected source
subcategory and proves the recognition formulas (A.3) and (A.4). It does not
assume those formulas, truncation stability, or boundedness. The only
large-category t-structure input on the source is the concrete output of
Theorem A.13: a `TStructure` together with its proved compact-generation
formula.

Scheme realization, bounded-coherent/perfect identification, and S-locality
are intentionally absent. They are the geometric layer of SF7.3.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open CategoryTheory.Triangulated

universe w v u₁ u₂

namespace CategoryTheory.Triangulated.Polishchuk

variable {C : Type u₁} [Category.{v} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C]
  {D : Type u₂} [Category.{v} D] [HasZeroObject D] [HasShift D ℤ]
  [Preadditive D] [∀ n : ℤ, (shiftFunctor D n).Additive]
  [Pretriangulated D]

/-- The bounded categorical output of A.17, with formulas (A.3) and (A.4)
stated against the restricted target t-structure. -/
structure InducedTStructureData
    (F : Functor C D) (P : ObjectProperty C) (Q : ObjectProperty D)
    [P.IsTriangulated] [Q.IsTriangulated]
    (tD : TStructure D) [Q.HasInducedTStructure tD]
    (hmem : ∀ X : C, P X ↔ Q (F.obj X)) where
  /-- The induced t-structure on the selected source subcategory. -/
  tStructure : TStructure P.FullSubcategory
  /-- Step 4: the induced t-structure is bounded. -/
  isBounded : TStructure.IsBounded tStructure
  /-- Formula (A.3), in every degree. -/
  isLE_iff (X : P.FullSubcategory) (n : ℤ) :
    tStructure.IsLE X n ↔
      (Q.tStructure tD).IsLE
        ((ObjectProperty.preimageLift F hmem).obj X) n
  /-- Formula (A.4), in every degree. -/
  isGE_iff (X : P.FullSubcategory) (n : ℤ) :
    tStructure.IsGE X n ↔
      (Q.tStructure tD).IsGE
        ((ObjectProperty.preimageLift F hmem).obj X) n

/- The `Q.lift` expressions above require literal preimage membership. The
following theorem therefore uses `P = Q.inverseImage F`; this is exactly the
object-property form of assumption (iv) in A.17. -/

/-- Theorem A.17, categorical Steps 1--4.

The target large t-structure is compactly generated by `G`; the source large
t-structure is the A.13 output generated by the left-adjoint image of `G`.
The monad hypothesis proves t-exactness. Detection of the selected
subcategories proves truncation stability, zero reflection proves both
recognition formulas, and boundedness descends from the restricted target.

Zero reflection is assumed only on objects whose image lies in the selected
target subcategory `Q` -- the object-property form of A.17's
conservativity-on-bounded-objects hypothesis. Until 2026-08-18 it was
demanded on the whole source category, which was sound but strictly stronger
than the source theorem and a materially harder obligation for the scheme
realization (adversarial review, finding P2-11). -/
noncomputable def induce
    {L : Functor D C} {F : Functor C D}
    [L.CommShift ℤ] [L.IsTriangulated]
    [F.Additive] [F.CommShift ℤ] [F.IsTriangulated]
    (adj : L ⊣ F)
    {tC : TStructure C} {tD : TStructure D}
    {G : ObjectProperty D} {Q : ObjectProperty D}
    [Q.IsTriangulated] [Q.IsClosedUnderIsomorphisms]
    [Q.HasInducedTStructure tD]
    (hF : F.PreservesSmallCoproducts.{w})
    (hD : tD.IsCompactlyGeneratedBy.{w} G)
    (hC : tC.IsCompactlyGeneratedBy.{w} (G.map L))
    (hmonad : (L ⋙ F).IsRightTExact tD tD)
    (hzero : ∀ E : C, Q (F.obj E) → IsZero (F.obj E) → IsZero E)
    (hbounded : TStructure.IsBounded (Q.tStructure tD)) :
    InducedTStructureData F (Q.inverseImage F) Q tD (fun _ ↦ Iff.rfl) := by
  let P := Q.inverseImage F
  letI : P.IsTriangulated := by
    dsimp only [P]
    infer_instance
  letI : F.IsTExact tC tD :=
    adj.isTExact_of_compactlyGenerated hF hD hC hmonad
  letI : P.HasInducedTStructure tC :=
    ObjectProperty.hasInducedTStructure_of_preimage
      (P := P) (Q := Q) (F := F) (t := tC) (t' := tD) (fun _ ↦ Iff.rfl)
  let tP := P.tStructure tC
  let liftF := ObjectProperty.preimageLift F (P := P) (Q := Q) (fun _ ↦ Iff.rfl)
  have hLE (X : P.FullSubcategory) (n : ℤ) :
      tP.IsLE X n ↔ (Q.tStructure tD).IsLE (liftF.obj X) n :=
    ObjectProperty.tStructure_isLE_iff_map
      (P := P) (Q := Q) (F := F) (t := tC) (t' := tD)
      hzero (fun _ ↦ Iff.rfl) X n
  have hGE (X : P.FullSubcategory) (n : ℤ) :
      tP.IsGE X n ↔ (Q.tStructure tD).IsGE (liftF.obj X) n :=
    ObjectProperty.tStructure_isGE_iff_map
      (P := P) (Q := Q) (F := F) (t := tC) (t' := tD)
      hzero (fun _ ↦ Iff.rfl) X n
  have hPbounded : TStructure.IsBounded tP := by
    intro X
    obtain ⟨⟨a, ha⟩, ⟨b, hb⟩⟩ := hbounded (liftF.obj X)
    exact ⟨⟨a, (hGE X a).2 ha⟩, ⟨b, (hLE X b).2 hb⟩⟩
  exact
    { tStructure := tP
      isBounded := hPbounded
      isLE_iff := hLE
      isGE_iff := hGE }

/-- The categorical A.17 constructor with the source t-structure assembled
directly from the A.13 approximation triangles.

Compactness of the source generators is derived from the adjunction and target
compactness. Thus the only source existence input is the honest Brown-
representability approximation output, not a pre-existing t-structure or its
compact-generation equality. -/
noncomputable def induceOfApproximation
    {L : Functor D C} {F : Functor C D}
    [L.CommShift ℤ] [L.IsTriangulated]
    [F.Additive] [F.CommShift ℤ] [F.IsTriangulated]
    (adj : L ⊣ F)
    {tD : TStructure D} {G : ObjectProperty D} {Q : ObjectProperty D}
    [Q.IsTriangulated] [Q.IsClosedUnderIsomorphisms]
    [Q.HasInducedTStructure tD]
    (hF : F.PreservesSmallCoproducts.{w})
    (hD : tD.IsCompactlyGeneratedBy.{w} G)
    (happrox : TStructure.CompactGeneratorApproximation.{w} (G.map L))
    (hmonad : (L ⋙ F).IsRightTExact tD tD)
    (hzero : ∀ E : C, Q (F.obj E) → IsZero (F.obj E) → IsZero E)
    (hbounded : TStructure.IsBounded (Q.tStructure tD)) :
    InducedTStructureData F (Q.inverseImage F) Q tD (fun _ ↦ Iff.rfl) :=
  induce adj hF hD
    (happrox.isCompactlyGeneratedBy
      (adj.compactObjects_map_leftAdjoint hF hD.compact))
    hmonad hzero hbounded

/-- The categorical A.17 constructor using the repository-owned Brown tower.

The source compact generators are the left-adjoint images of the target
generators. Their compactness follows from the adjunction and coproduct
preservation. The remaining size and shift-closure assumptions are stated
explicitly, so no approximation-map or global inducing theorem is accepted
from the caller. -/
noncomputable def induceOfBrown
    {L : Functor D C} {F : Functor C D}
    [L.CommShift ℤ] [L.IsTriangulated]
    [F.Additive] [F.CommShift ℤ] [F.IsTriangulated]
    (adj : L ⊣ F)
    {tD : TStructure D} {G : ObjectProperty D} {Q : ObjectProperty D}
    [Q.IsTriangulated] [Q.IsClosedUnderIsomorphisms]
    [Q.HasInducedTStructure tD]
    [ObjectProperty.Small.{0} (G.map L)] [LocallySmall.{0} C]
    [HasCoproducts.{0} C]
    (hF : F.PreservesSmallCoproducts.{0})
    (hD : tD.IsCompactlyGeneratedBy.{0} G)
    (hshift : G.map L ≤ (G.map L).shift (1 : ℤ))
    (hmonad : (L ⋙ F).IsRightTExact tD tD)
    (hzero : ∀ E : C, Q (F.obj E) → IsZero (F.obj E) → IsZero E)
    (hbounded : TStructure.IsBounded (Q.tStructure tD)) :
    InducedTStructureData F (Q.inverseImage F) Q tD (fun _ ↦ Iff.rfl) :=
  induceOfApproximation adj hF hD
    (TStructure.CompactGeneratorBrown.compactGeneratorApproximation
      (G := G.map L) hshift
      (adj.compactObjects_map_leftAdjoint hF hD.compact))
    hmonad hzero hbounded

/-- The categorical A.17 constructor from Brown-style universal maps.

The source approximation triangles and the proof that their cones are right
orthogonal are both constructed internally.  The remaining representability
input is precisely the existence of universal maps with the two Hom controls
recorded by `TStructure.ApproximationMap`. -/
noncomputable def induceOfApproximationMaps
    {L : Functor D C} {F : Functor C D}
    [L.CommShift ℤ] [L.IsTriangulated]
    [F.Additive] [F.CommShift ℤ] [F.IsTriangulated]
    (adj : L ⊣ F)
    {tD : TStructure D} {G : ObjectProperty D} {Q : ObjectProperty D}
    [Q.IsTriangulated] [Q.IsClosedUnderIsomorphisms]
    [Q.HasInducedTStructure tD]
    (hF : F.PreservesSmallCoproducts.{w})
    (hD : tD.IsCompactlyGeneratedBy.{w} G)
    (hshift : G.map L ≤ (G.map L).shift (1 : ℤ))
    (happrox : ∀ A : C,
      Nonempty (TStructure.ApproximationMap (G.map L).coprodClosure.{w} A))
    (hmonad : (L ⋙ F).IsRightTExact tD tD)
    (hzero : ∀ E : C, Q (F.obj E) → IsZero (F.obj E) → IsZero E)
    (hbounded : TStructure.IsBounded (Q.tStructure tD)) :
    InducedTStructureData F (Q.inverseImage F) Q tD (fun _ ↦ Iff.rfl) :=
  induceOfApproximation adj hF hD
    (TStructure.CompactGeneratorApproximation.ofApproximationMaps hshift happrox)
    hmonad hzero hbounded

end CategoryTheory.Triangulated.Polishchuk
