/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import BridgelandStabLean.StabilityCondition.Symmetry.Autoequivalence.Foundations.GrothendieckGroup
import BridgelandStabLean.StabilityCondition.Symmetry.Autoequivalence.Slicing.Transport
import BridgelandStabLean.Foundation

/-!
# Transporting strict finite length along functors

The reusable centrepiece of the third piece the `Aut` action on stability
conditions needs.

The foundational library has a general transfer lemma,
`isStrictArtinianObject_of_faithful_map_strictMono`
(`QuasiAbelian/Basic.lean:691`), for any full+faithful strict-mono-preserving
functor — but it assumes **ordinary** `IsArtinianObject` of the image (DCC on
*all* subobjects), which is strictly stronger than what `Slicing.IsLocallyFinite`
supplies. The versions that assume only *strict* finite length exist solely as
`interval_strictArtinianObject_of_inclusion_strict` and its Noetherian twin
(`Deformation/IntervalSelection.lean:206`, `:274`), each hand-rolling a ~70-line
`StrictSubobject` order-embedding for the specific functor `ObjectProperty.ιOfLE`.

This file extracts that argument once, for an arbitrary functor. The foundational library's
own two interval lemmas are instances of it.

## The extra hypothesis, and why it is unavoidable here

`harr` says the *arrow of the subobject generated by* a strict mono is again a
strict mono. It cannot be dropped: proving it needs strict monos to be closed
under composition (with `Subobject.underlyingIso`), and **strict-mono
composition is not available in general** — the foundational library proves it only for
interval categories (`Slicing.IntervalCat.comp_strictMono`,
`IntervalCategory/FiniteLength.lean:189`). Callers whose target is an interval
category discharge `harr` with
`intervalSubobject_arrow_strictMono_of_strictMono`.

## Also here

`mapEquiv_intervalProp_iff`: under the `Aut` action the interval endpoints do
**not** move — only the objects do. That is the structural difference from step
3c, where the endpoints moved and `exists_radius` was needed. It is why the
foundational library's `interval_thinFiniteLength_of_inclusion_strict` cannot be reused for
`Aut`: it compares two `intervalProp`s on the *same* object.
-/

open BridgelandStabLean.Foundation
open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated

namespace BridgelandStabLean.Foundation

open BridgelandStabLean.Foundation

universe w u

/-! ## The general transfer -/

section Transfer

variable {A : Type u} [Category.{w} A] [Preadditive A] [HasKernels A] [HasCokernels A]
variable {D : Type u} [Category.{w} D] [Preadditive D] [HasKernels D] [HasCokernels D]

variable (F : A ⥤ D) [F.Full] [F.Faithful]
  (hF : ∀ {X Y : A} (f : X ⟶ Y), IsStrictMono f → IsStrictMono (F.map f))
  (harr : ∀ {Y Z : D} (f : Y ⟶ Z) [Mono f], IsStrictMono f →
    IsStrictMono (Subobject.mk f).arrow)

/-- The image of a strict subobject, landing in **strict** subobjects — which
is what lets the hypothesis be strict rather than ordinary. -/
noncomputable def strictImage {E : A} : StrictSubobject E → StrictSubobject (F.obj E) :=
  fun B =>
    letI hs : IsStrictMono (F.map B.1.arrow) := hF B.1.arrow B.2
    letI : Mono (F.map B.1.arrow) := hs.mono
    ⟨Subobject.mk (F.map B.1.arrow), harr _ hs⟩

omit [F.Full] [F.Faithful] in
theorem strictImage_monotone {E : A} :
    Monotone (strictImage F hF harr (E := E)) := by
  intro B₁ B₂ hB
  letI hs₁ : IsStrictMono (F.map B₁.1.arrow) := hF B₁.1.arrow B₁.2
  letI hs₂ : IsStrictMono (F.map B₂.1.arrow) := hF B₂.1.arrow B₂.2
  letI : Mono (F.map B₁.1.arrow) := hs₁.mono
  letI : Mono (F.map B₂.1.arrow) := hs₂.mono
  have hB' : B₁.1 ≤ B₂.1 := by simpa using hB
  have hmk : Subobject.mk B₁.1.arrow ≤ Subobject.mk B₂.1.arrow := by
    simpa [Subobject.mk_arrow] using hB'
  show Subobject.mk (F.map B₁.1.arrow) ≤ Subobject.mk (F.map B₂.1.arrow)
  exact Subobject.mk_le_mk_of_comm (F.map (Subobject.ofMkLEMk B₁.1.arrow B₂.1.arrow hmk)) (by
    rw [← F.map_comp]; exact congrArg F.map (Subobject.ofMkLEMk_comp hmk))

theorem strictImage_injective {E : A} :
    Function.Injective (strictImage F hF harr (E := E)) := by
  intro B₁ B₂ hEq
  letI hs₁ : IsStrictMono (F.map B₁.1.arrow) := hF B₁.1.arrow B₁.2
  letI hs₂ : IsStrictMono (F.map B₂.1.arrow) := hF B₂.1.arrow B₂.2
  letI : Mono (F.map B₁.1.arrow) := hs₁.mono
  letI : Mono (F.map B₂.1.arrow) := hs₂.mono
  apply Subtype.ext
  have hEq' : Subobject.mk (F.map B₁.1.arrow) = Subobject.mk (F.map B₂.1.arrow) :=
    congrArg Subtype.val hEq
  simpa [Subobject.mk_arrow] using
    (Subobject.mk_eq_mk_of_comm B₁.1.arrow B₂.1.arrow
      (F.preimageIso (Subobject.isoOfMkEqMk _ _ hEq'))
      (F.map_injective (by
        simp only [Functor.preimageIso_hom, Functor.map_comp, Functor.map_preimage]
        exact Subobject.ofMkLEMk_comp hEq'.le)))

/-- Monotone + injective on a partial order is strictly monotone, which is what
pulls well-foundedness back. -/
theorem strictImage_strictMono {E : A} {a b : StrictSubobject E} (hab : a < b) :
    strictImage F hF harr a < strictImage F hF harr b :=
  lt_of_le_of_ne (strictImage_monotone F hF harr hab.le)
    (fun h => absurd (strictImage_injective F hF harr h) (ne_of_lt hab))

include hF harr in
/-- **Strict-Artinian transfers, from a strict hypothesis.** The foundational library's
`isStrictArtinianObject_of_faithful_map_strictMono` needs ordinary
`IsArtinianObject` of the image; this needs only the strict version. -/
theorem isStrictArtinian_of_faithful_strict {E : A}
    [IsStrictArtinianObject (F.obj E)] : IsStrictArtinianObject E :=
  ObjectProperty.is_of_prop _
    (show WellFoundedLT (StrictSubobject E) from
      ⟨Subrelation.wf (strictImage_strictMono F hF harr)
        (InvImage.wf _ IsWellFounded.wf)⟩)

include hF harr in
/-- Strict-Noetherian, the same route with the order reversed. -/
theorem isStrictNoetherian_of_faithful_strict {E : A}
    [IsStrictNoetherianObject (F.obj E)] : IsStrictNoetherianObject E := by
  refine ObjectProperty.is_of_prop _ ⟨?_⟩
  have hw : WellFounded (InvImage (· > · : StrictSubobject (F.obj E) → _ → Prop)
      (strictImage F hF harr)) := InvImage.wf _ IsWellFounded.wf
  refine Subrelation.wf ?_ hw
  intro a b hab
  exact strictImage_strictMono F hF harr hab

end Transfer

/-! ## Strict finite length along inclusions of thin interval categories -/

section IntervalInclusion

variable {C : Type u} [Category.{w} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
  [IsTriangulated C]

/-- Strict Artinian and Noetherian conditions pull back from a containing
thin interval. -/
theorem interval_thinFiniteLength_of_inclusion_strict
    {s₁ s₂ : Slicing C} {a₁ b₁ a₂ b₂ : ℝ}
    [Fact (a₁ < b₁)] [Fact (b₁ - a₁ ≤ 1)]
    [Fact (a₂ < b₂)] [Fact (b₂ - a₂ ≤ 1)]
    (h : s₁.intervalProp C a₁ b₁ ≤ s₂.intervalProp C a₂ b₂)
    (hFinite : ∀ Y : s₂.IntervalCat C a₂ b₂,
      IsStrictArtinianObject Y ∧ IsStrictNoetherianObject Y) :
    ∀ X : s₁.IntervalCat C a₁ b₁,
      IsStrictArtinianObject X ∧ IsStrictNoetherianObject X := by
  intro X
  let I := ObjectProperty.ιOfLE h
  have hBig := hFinite (I.obj X)
  letI : IsStrictArtinianObject (I.obj X) := hBig.1
  letI : IsStrictNoetherianObject (I.obj X) := hBig.2
  have hmap : ∀ {A B : s₁.IntervalCat C a₁ b₁} (f : A ⟶ B),
      IsStrictMono f → IsStrictMono (I.map f) := by
    intro A B f hf
    exact intervalInclusion_map_strictMono (C := C) h f hf
  have harr : ∀ {A B : s₂.IntervalCat C a₂ b₂} (f : A ⟶ B) [Mono f],
      IsStrictMono f → IsStrictMono (Subobject.mk f).arrow := by
    intro A B f _ hf
    exact intervalSubobject_arrow_strictMono (C := C) f hf
  exact ⟨isStrictArtinian_of_faithful_strict I hmap harr,
    isStrictNoetherian_of_faithful_strict I hmap harr⟩

/-- An admissible subobject stays admissible when its thin interval is
included in another thin interval. -/
theorem intervalInclusion_isAdmissibleSubobject
    {s₁ s₂ : Slicing C} {a₁ b₁ a₂ b₂ : ℝ}
    [Fact (a₁ < b₁)] [Fact (b₁ - a₁ ≤ 1)]
    [Fact (a₂ < b₂)] [Fact (b₂ - a₂ ≤ 1)]
    (h : s₁.intervalProp C a₁ b₁ ≤ s₂.intervalProp C a₂ b₂)
    {E : s₁.IntervalCat C a₁ b₁} (A : Subobject E)
    (hA : s₁.IsAdmissibleSubobject C A) :
    s₂.IsAdmissibleSubobject C
      (strictSubobjectImageOfFullFaithful (ObjectProperty.ιOfLE h)
        (fun f hf ↦ intervalInclusion_map_strictMono (C := C) h f hf)
        ⟨A, Slicing.IntervalCat.isStrictSubobject_of_isAdmissible C s₁ A hA⟩) := by
  rcases hA with ⟨Y, Q, i, hi, q, hAi, δ, hT⟩
  let I := ObjectProperty.ιOfLE h
  have hiStrict : IsStrictMono i := by
    let S : ShortComplex (s₁.IntervalCat C a₁ b₁) :=
      ShortComplex.mk i q (by
        apply (s₁.intervalProp C a₁ b₁).ι.map_injective
        exact comp_distTriang_mor_zero₁₂ _ hT)
    have hS := Slicing.IntervalCat.strictShortExact_of_distinguished
      (S := S) (δ := δ) C s₁ hT
    exact ⟨hS.shortExact.mono_f, hS.strict_f⟩
  have hImap : IsStrictMono (I.map i) :=
    intervalInclusion_map_strictMono (C := C) h i hiStrict
  letI : Mono (I.map i) := hImap.mono
  refine ⟨I.obj Y, I.obj Q, I.map i, inferInstance, I.map q, ?_, δ, ?_⟩
  · subst A
    have hcanonical : IsStrictMono (Subobject.mk i).arrow :=
      BridgelandStabLean.Foundation.Deformation.Slicing.IntervalCat.subobject_arrow_strictMono
        C i hiStrict
    have hcanonicalMap : IsStrictMono (I.map (Subobject.mk i).arrow) :=
      intervalInclusion_map_strictMono (C := C) h _ hcanonical
    letI : Mono (I.map (Subobject.mk i).arrow) := hcanonicalMap.mono
    apply Subobject.mk_eq_mk_of_comm
      (I.map i) (I.map (Subobject.mk i).arrow)
      (I.mapIso (Subobject.underlyingIso i)).symm
    simpa only [Functor.map_comp, Iso.symm_hom, Functor.mapIso_inv] using
      congrArg I.map (Subobject.underlyingIso_arrow i)
  · dsimp [I, ObjectProperty.ιOfLE]
    exact hT

/-- Intrinsic admissible finite length pulls back along an inclusion of thin
interval categories. -/
theorem interval_finiteLength_of_inclusion
    {s₁ s₂ : Slicing C} {a₁ b₁ a₂ b₂ : ℝ}
    [Fact (a₁ < b₁)] [Fact (b₁ - a₁ ≤ 1)]
    [Fact (a₂ < b₂)] [Fact (b₂ - a₂ ≤ 1)]
    (h : s₁.intervalProp C a₁ b₁ ≤ s₂.intervalProp C a₂ b₂)
    (hFinite : ∀ Y : s₂.IntervalCat C a₂ b₂,
      s₂.IsFiniteLength C Y) :
    ∀ X : s₁.IntervalCat C a₁ b₁, s₁.IsFiniteLength C X := by
  intro X
  let I := ObjectProperty.ιOfLE h
  let hmap : ∀ {A B : s₁.IntervalCat C a₁ b₁} (f : A ⟶ B),
      IsStrictMono f → IsStrictMono (I.map f) := by
    intro A B f hf
    exact intervalInclusion_map_strictMono (C := C) h f hf
  let AtoS := Slicing.IntervalCat.admissibleToStrictSubobject C s₁ X
  let F : s₁.AdmissibleSubobject C X → s₂.AdmissibleSubobject C (I.obj X) :=
    fun A ↦ ⟨strictSubobjectImageOfFullFaithful I hmap (AtoS A),
      intervalInclusion_isAdmissibleSubobject (C := C) h A.1 A.2⟩
  have hFmono : Monotone F := by
    intro A B hAB
    exact strictSubobjectImageOfFullFaithful_monotone I hmap
      (AtoS.monotone hAB)
  have hFinj : Function.Injective F := by
    intro A B hAB
    apply AtoS.injective
    apply strictSubobjectImageOfFullFaithful_injective I hmap
    exact congrArg Subtype.val hAB
  have hFstrictLT : ∀ {A B : s₁.AdmissibleSubobject C X}, A < B → F A < F B := by
    intro A B hAB
    exact lt_of_le_of_ne (hFmono hAB.le)
      (fun hEq ↦ hAB.ne (hFinj hEq))
  have hFstrictGT : ∀ {A B : s₁.AdmissibleSubobject C X}, A > B → F A > F B := by
    intro A B hAB
    exact hFstrictLT hAB
  have hBig := hFinite (I.obj X)
  constructor
  · letI : WellFoundedLT (s₂.AdmissibleSubobject C (I.obj X)) := hBig.1
    exact ⟨Subrelation.wf hFstrictLT
      (InvImage.wf F (show WellFounded ((· < ·) :
        s₂.AdmissibleSubobject C (I.obj X) → _ → Prop) from IsWellFounded.wf))⟩
  · letI : WellFoundedGT (s₂.AdmissibleSubobject C (I.obj X)) := hBig.2
    exact ⟨Subrelation.wf hFstrictGT
      (InvImage.wf F (show WellFounded ((· > ·) :
        s₂.AdmissibleSubobject C (I.obj X) → _ → Prop) from IsWellFounded.wf))⟩

end IntervalInclusion

/-! ## Interval properties under the `Aut` action -/

section Aut

variable {C : Type u} [Category.{w} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]

variable (Φ : C ≌ C)
  [Φ.functor.Additive] [Φ.inverse.Additive]
  [Φ.functor.CommShift ℤ] [Φ.inverse.CommShift ℤ]
  [Φ.functor.IsTriangulated] [Φ.inverse.IsTriangulated]

/-- **The endpoints do not move.** An autoequivalence relabels *objects*, so
`E` lies in the `(a, b)` window of `Φ • s` exactly when `Φ⁻¹ E` lies in the
same `(a, b)` window of `s`.

Contrast `relabel_intervalProp`, where phase relabelling moves the endpoints
and requires a uniform-continuity argument. -/
theorem mapEquiv_intervalProp_iff (s : Slicing C) (a b : ℝ) (E : C) :
    (s.mapEquiv Φ).intervalProp C a b E
      ↔ s.intervalProp C a b (Φ.inverse.obj E) := by
  constructor
  · rintro (hz | ⟨F, hF⟩)
    · exact Or.inl (Φ.inverse.map_isZero hz)
    · exact Or.inr
        ⟨BridgelandStabLean.Foundation.HNFiltration.mapF F
          (P' := s.P) Φ.inverse (fun _ _ h => h), hF⟩
  · rintro (hz | ⟨G, hG⟩)
    · exact Or.inl (IsZero.of_iso (Φ.functor.map_isZero hz) (Φ.counitIso.app E).symm)
    · exact Or.inr
        ⟨BridgelandStabLean.Foundation.HNFiltration.ofIso C
          (BridgelandStabLean.Foundation.HNFiltration.mapF G
            (P' := fun φ X => s.P φ (Φ.inverse.obj X)) Φ.functor
            (fun _ X h => ObjectProperty.prop_of_iso _ (Φ.unitIso.app X) h))
          (Φ.counitIso.app E), hG⟩

end Aut

end BridgelandStabLean.Foundation
