import DerivedAlgGeo.AlgebraicGeometry.RiemannRoch.Surface.Divisor
import DerivedAlgGeo.AlgebraicGeometry.RiemannRoch.Surface.NumericalVariety
import DerivedAlgGeo.AlgebraicGeometry.RiemannRoch.Surface.ToddData
import DerivedAlgGeo.AlgebraicGeometry.RiemannRoch.Surface.Devissage
import DerivedAlgGeo.AlgebraicGeometry.RiemannRoch.Surface.Assembly
