/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import BridgelandStabLean.StabilityCondition.Symmetry.Combined.Action
import BridgelandStability.StabilityCondition.ConnectedComponent
import Mathlib.Topology.Algebra.ConstMulAction

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

/-!
# Topology of the combined symmetry action

The Bridgeland topology is generated by the sets `basisNhd C σ ε`.  This file
shows that a compatible autoequivalence pair carries each such neighborhood into
the neighborhood with the same radius at the transported centre.  Consequently
every element of `AutPairQuot v` acts by a homeomorphism.

Only a one-sided estimate is needed for continuity.  The inverse group element
supplies the opposite direction automatically through `Homeomorph.smul`.
-/

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated
open CategoryTheory.Triangulated

namespace BridgelandStabLean.GroupAction

noncomputable section

universe w u u'

variable {C : Type u} [Category.{w} C] [HasZeroObject C] [HasShift C ℤ]
  [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
variable {Λ : Type u'} [AddCommGroup Λ] {v : K₀ C →+ Λ}

namespace Slicing

variable (s : Slicing C) (a : AutPair v) (E : C) (hE : ¬IsZero E)

/-- The inverse image of a nonzero object under an equivalence is nonzero. -/
private theorem inverse_obj_nonzero (a : AutPair v) (E : C) (hE : ¬IsZero E) :
    ¬IsZero (a.Φ.e.inverse.obj E) := by
  intro h
  exact hE (IsZero.of_iso (a.Φ.e.functor.map_isZero h) (a.Φ.e.counitIso.app E).symm)

/-- Transport by an autoequivalence does not change the largest HN phase; it
only replaces the object by its inverse image. -/
theorem mapEquiv_phiPlus :
    (s.mapEquiv a.Φ.e).phiPlus C E hE =
      s.phiPlus C (a.Φ.e.inverse.obj E) (inverse_obj_nonzero a E hE) := by
  let hE' := inverse_obj_nonzero a E hE
  obtain ⟨G, hn, hfirst, hlast⟩ := HNFiltration.exists_both_nonzero C s hE'
  let F₀ := G.mapF (P' := fun φ X ↦ s.P φ (a.Φ.e.inverse.obj X)) a.Φ.e.functor
    (fun _ X h ↦ ObjectProperty.prop_of_iso _ (a.Φ.e.unitIso.app X) h)
  let F := F₀.ofIso C (a.Φ.e.counitIso.app E)
  have hfirst' : ¬IsZero (F.triangle ⟨0, hn⟩).obj₃ := by
    intro h
    apply hfirst
    exact IsZero.of_iso (a.Φ.e.inverse.map_isZero h) (a.Φ.e.unitIso.app _)
  rw [(s.mapEquiv a.Φ.e).phiPlus_eq C E hE F hn hfirst',
    s.phiPlus_eq C (a.Φ.e.inverse.obj E) hE' G hn hfirst]
  rfl

/-- Transport by an autoequivalence does not change the smallest HN phase; it
only replaces the object by its inverse image. -/
theorem mapEquiv_phiMinus :
    (s.mapEquiv a.Φ.e).phiMinus C E hE =
      s.phiMinus C (a.Φ.e.inverse.obj E) (inverse_obj_nonzero a E hE) := by
  let hE' := inverse_obj_nonzero a E hE
  obtain ⟨G, hn, hfirst, hlast⟩ := HNFiltration.exists_both_nonzero C s hE'
  let F₀ := G.mapF (P' := fun φ X ↦ s.P φ (a.Φ.e.inverse.obj X)) a.Φ.e.functor
    (fun _ X h ↦ ObjectProperty.prop_of_iso _ (a.Φ.e.unitIso.app X) h)
  let F := F₀.ofIso C (a.Φ.e.counitIso.app E)
  have hlast' : ¬IsZero (F.triangle ⟨F.n - 1, by
      simpa [F, F₀, HNFiltration.ofIso, HNFiltration.mapF, PostnikovTower.mapF] using
        Nat.sub_one_lt (Nat.ne_of_gt hn)⟩).obj₃ := by
    change ¬IsZero (a.Φ.e.functor.obj (G.triangle ⟨G.n - 1, by lia⟩).obj₃)
    intro h
    apply hlast
    exact IsZero.of_iso (a.Φ.e.inverse.map_isZero h) (a.Φ.e.unitIso.app _)
  rw [(s.mapEquiv a.Φ.e).phiMinus_eq C E hE F hn hlast',
    s.phiMinus_eq C (a.Φ.e.inverse.obj E) hE' G hn hlast]
  rfl

end Slicing

/-- An autoequivalence does not increase the generalized slicing distance. -/
theorem slicingDist_mapEquiv_le (a : AutPair v) (s₁ s₂ : Slicing C) :
    slicingDist C (s₁.mapEquiv a.Φ.e) (s₂.mapEquiv a.Φ.e) ≤
      slicingDist C s₁ s₂ := by
  apply iSup_le
  intro E
  apply iSup_le
  intro hE
  rw [Slicing.mapEquiv_phiPlus s₁ a E hE, Slicing.mapEquiv_phiPlus s₂ a E hE,
    Slicing.mapEquiv_phiMinus s₁ a E hE, Slicing.mapEquiv_phiMinus s₂ a E hE]
  exact le_iSup_of_le (a.Φ.e.inverse.obj E)
    (le_iSup_of_le (Slicing.inverse_obj_nonzero a E hE) le_rfl)

variable [IsTriangulated C]

/-- The seminorm of a transported charge difference is no larger than the
original seminorm. -/
theorem stabSeminorm_aut_le (a : AutPair v)
    (σ τ : StabilityCondition.WithClassMap C v) :
    stabSeminorm C (a.act σ) ((a.act τ).Z - (a.act σ).Z) ≤
      stabSeminorm C σ (τ.Z - σ.Z) := by
  apply iSup_le
  intro E
  apply iSup_le
  intro φ
  apply iSup_le
  intro hP
  apply iSup_le
  intro hE
  let hE' := Slicing.inverse_obj_nonzero a E hE
  have hcl : a.lam (cl C v E) = cl C v (a.Φ.e.inverse.obj E) := by
    rw [cl, ← a.compat, K₀.mapF_of]
  have hcharge : (a.act σ).charge E = σ.charge (a.Φ.e.inverse.obj E) := by
    change σ.Z (a.lam (cl C v E)) = _
    rw [hcl]
  have hnum : ((a.act τ).Z - (a.act σ).Z) (cl C v E) =
      (τ.Z - σ.Z) (cl C v (a.Φ.e.inverse.obj E)) := by
    change τ.Z (a.lam (cl C v E)) - σ.Z (a.lam (cl C v E)) =
      τ.Z (cl C v (a.Φ.e.inverse.obj E)) -
        σ.Z (cl C v (a.Φ.e.inverse.obj E))
    rw [hcl]
  rw [hnum, hcharge]
  exact le_iSup_of_le (a.Φ.e.inverse.obj E)
    (le_iSup_of_le φ (le_iSup_of_le hP (le_iSup_of_le hE' le_rfl)))

/-- A representative autoequivalence pair carries a basic neighborhood into
the basic neighborhood of the transported centre, with unchanged radius. -/
theorem AutPair.mapsTo_basisNhd (a : AutPair v)
    (σ : StabilityCondition.WithClassMap C v) (ε : ℝ) :
    Set.MapsTo a.act (basisNhd C σ ε) (basisNhd C (a.act σ) ε) := by
  intro τ hτ
  constructor
  · exact lt_of_le_of_lt (stabSeminorm_aut_le a σ τ) hτ.1
  · exact lt_of_le_of_lt (slicingDist_mapEquiv_le a σ.slicing τ.slicing) hτ.2

/-- Every fixed compatible autoequivalence acts continuously on the
Bridgeland stability space. -/
theorem AutPair.continuous_act (a : AutPair v) : Continuous a.act := by
  rw [continuous_generateFrom_iff]
  rintro U ⟨ξ, ε, hε, hε8, rfl⟩
  rw [isOpen_iff_mem_nhds]
  intro τ hτ
  change a.act τ ∈ basisNhd C ξ ε at hτ
  obtain ⟨δ, hδ, hδ8, hsub⟩ := exists_basisNhd_subset_basisNhd C ξ (a.act τ) hε hε8 hτ
  refine mem_nhds_iff.mpr ⟨basisNhd C τ δ, ?_, ?_, basisNhd_self C τ hδ hδ8⟩
  · exact fun ρ hρ ↦ hsub (a.mapsTo_basisNhd τ δ hρ)
  · exact TopologicalSpace.isOpen_generateFrom_of_mem ⟨τ, δ, hδ, hδ8, rfl⟩

/-- The quotient action is continuous in the stability-condition variable. -/
noncomputable instance autPairQuotContinuousConstSMul :
    ContinuousConstSMul (AutPairQuot v) (StabilityCondition.WithClassMap C v) where
  continuous_const_smul q := by
    induction q using Quotient.inductionOn with
    | _ a => exact a.continuous_act

/-- A named homeomorphism for each compatible autoequivalence class. -/
noncomputable def AutPairQuot.homeomorph (q : AutPairQuot v) :
    StabilityCondition.WithClassMap C v ≃ₜ StabilityCondition.WithClassMap C v :=
  Homeomorph.smul q

end

end BridgelandStabLean.GroupAction
