/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under the MIT license.
-/
import DerivedAlgGeo.CategoryTheory.Triangulated.StabilityCondition.Foundation.PostnikovTower
import Mathlib.CategoryTheory.Triangulated.Subcategory

/-!
# Owner extension closure

The extension closure generated by an object property is defined intrinsically
from distinguished triangles.  This owner-namespaced construction feeds the
deformed phase cuts entirely within the repository-owned foundation.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated

universe u v

namespace CategoryTheory.Triangulated

/-- The owner extension closure generated by an object property. -/
inductive ExtensionClosure {C : Type u} [Category.{v} C]
    [HasZeroObject C] [HasShift C ℤ] [Preadditive C]
    [∀ n : ℤ, (shiftFunctor C n).Additive] [Pretriangulated C]
    (P : CategoryTheory.ObjectProperty C) : CategoryTheory.ObjectProperty C where
  | zero {E : C} : IsZero E → ExtensionClosure P E
  | mem {E : C} : P E → ExtensionClosure P E
  | ext {X E Y : C} {f : X ⟶ E} {g : E ⟶ Y} {h : Y ⟶ X⟦(1 : ℤ)⟧} :
      Triangle.mk f g h ∈ distTriang C →
      ExtensionClosure P X → ExtensionClosure P Y →
      ExtensionClosure P E

namespace ExtensionClosure

/-- Owner extension closure is monotone in its generators. -/
theorem mono {C : Type u} [Category.{v} C] [HasZeroObject C]
    [HasShift C ℤ] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive]
    [Pretriangulated C] {P Q : CategoryTheory.ObjectProperty C} (h : P ≤ Q) :
    ExtensionClosure P ≤ ExtensionClosure Q := by
  intro E hE
  induction hE with
  | zero hzero => exact .zero hzero
  | mem hP => exact .mem (h _ hP)
  | ext hT _ _ ihX ihY => exact .ext hT ihX ihY

/-- Orthogonal generators have orthogonal owner extension closures. -/
theorem hom_eq_zero {C : Type u} [Category.{v} C] [HasZeroObject C]
    [HasShift C ℤ] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive]
    [Pretriangulated C] {P Q : CategoryTheory.ObjectProperty C}
    (h : ∀ (E F : C), P E → Q F → ∀ f : E ⟶ F, f = 0)
    {E F : C} (hE : ExtensionClosure P E) (hF : ExtensionClosure Q F)
    (f : E ⟶ F) : f = 0 := by
  induction hE generalizing F with
  | zero hzero => exact hzero.eq_of_src f 0
  | mem hP =>
      induction hF with
      | zero hzero => exact hzero.eq_of_tgt f 0
      | mem hQ => exact h _ _ hP hQ f
      | ext hT _ _ ihX ihY =>
          obtain ⟨g, rfl⟩ := Triangle.coyoneda_exact₂ _ hT f (ihY _)
          rw [ihX g]
          exact zero_comp
  | ext hT _ _ ihX ihY =>
      obtain ⟨g, rfl⟩ := Triangle.yoneda_exact₂ _ hT f (ihX hF _)
      rw [ihY hF g]
      exact comp_zero

/-- Owner extension closure is invariant under isomorphism. -/
theorem ofIso {C : Type u} [Category.{v} C] [HasZeroObject C]
    [HasShift C ℤ] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive]
    [Pretriangulated C] {P : CategoryTheory.ObjectProperty C} {X Y : C}
    (e : X ≅ Y) (h : ExtensionClosure P X) : ExtensionClosure P Y := by
  obtain ⟨Z, g, k, hT⟩ := distinguished_cocone_triangle e.hom
  have hZ : IsZero Z := (Triangle.isZero₃_iff_isIso₁ _ hT).mpr
    (show IsIso (Triangle.mk e.hom g k).mor₁ from e.isIso_hom)
  exact .ext hT h (.zero hZ)

/-- Walking an owner Postnikov tower assembles extension-closure membership
from membership of all factors. -/
theorem ofPostnikovTower {C : Type u} [Category.{v} C] [HasZeroObject C]
    [HasShift C ℤ] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive]
    [Pretriangulated C] {Q : CategoryTheory.ObjectProperty C} {E : C}
    (P : PostnikovTower C E) (hfactors : ∀ i, Q (P.factor i)) :
    ExtensionClosure Q E := by
  suffices h : ∀ k (hk : k ≤ P.n),
      ExtensionClosure Q (P.chain.obj' k (by omega)) by
    exact ofIso (Classical.choice P.top_iso) (h P.n le_rfl)
  intro k
  induction k with
  | zero =>
      intro _
      exact .zero P.base_isZero
  | succ k ih =>
      intro hk
      have hchain := ih (by omega)
      let T := P.triangle ⟨k, by omega⟩
      have hT := P.triangle_dist ⟨k, by omega⟩
      let e₁ := Classical.choice (P.triangle_obj₁ ⟨k, by omega⟩)
      let e₂ := Classical.choice (P.triangle_obj₂ ⟨k, by omega⟩)
      exact ofIso e₂ (ExtensionClosure.ext hT
        (ofIso e₁.symm hchain) (.mem (hfactors ⟨k, by omega⟩)))

instance {C : Type u} [Category.{v} C] [HasZeroObject C]
    [HasShift C ℤ] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive]
    [Pretriangulated C] (P : CategoryTheory.ObjectProperty C) :
    (ExtensionClosure P).IsClosedUnderIsomorphisms where
  of_iso e h := ofIso e h

/-- Induction principle into any object property containing zero and the
generators and closed under distinguished extensions. -/
theorem le_of_closed {C : Type u} [Category.{v} C] [HasZeroObject C]
    [HasShift C ℤ] [Preadditive C] [∀ n : ℤ, (shiftFunctor C n).Additive]
    [Pretriangulated C] {P Q : CategoryTheory.ObjectProperty C}
    (hzero : ∀ {E : C}, IsZero E → Q E) (hmem : P ≤ Q)
    (hext : ∀ {X E Y : C} {f : X ⟶ E} {g : E ⟶ Y} {h : Y ⟶ X⟦(1 : ℤ)⟧},
      Triangle.mk f g h ∈ distTriang C → Q X → Q Y → Q E) :
    ExtensionClosure P ≤ Q := by
  intro E hE
  induction hE with
  | zero hZ => exact hzero hZ
  | mem hP => exact hmem _ hP
  | ext hT _ _ ihX ihY => exact hext hT ihX ihY

end ExtensionClosure

end CategoryTheory.Triangulated
