/-
Copyright (c) 2026 Chris Dare. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import CohLean.Cohomology.Cech.BasisComparison
import CohLean.Cohomology.Derived.AffineVanishing
import CohLean.Cohomology.EulerCharacteristic.Basic
import Mathlib.AlgebraicGeometry.Morphisms.Affine
import Mathlib.AlgebraicGeometry.Morphisms.QuasiCompact
import Mathlib.CategoryTheory.Abelian.GrothendieckAxioms.Sheaf
import Mathlib.CategoryTheory.Sites.SheafCohomology.MayerVietoris
import Mathlib.Topology.Sheaves.Abelian
import Mathlib.Topology.Sheaves.MayerVietoris

/-!
# Cohomological boundedness from a finite acyclic open cover

This file isolates the finite-cover part of the usual cohomological-dimension argument.  A
nonempty list of opens is `IntersectionAcyclic` when the coefficient sheaf has vanishing
positive local cohomology on every nonempty intersection of members of the list.  Repeated
Mayer--Vietoris then shows that the cohomology of their union vanishes in every degree at least
the length of the list.

Using a recursive predicate keeps the statement independent of a choice of ordering while
avoiding any appeal to a normalized Cech complex.  The latter distinction matters in the
current Mathlib API: the raw ordered-tuple Cech complex has nonzero terms in arbitrarily high
degrees even for a finite cover.
-/

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace

namespace CategoryTheory.Sheaf

variable {X : TopCat.{u}}

set_option synthInstance.maxHeartbeats 800000
set_option maxHeartbeats 4000000
set_option maxRecDepth 10000

/-- The union of a finite list of opens. -/
def opensUnion : List (Opens X) → Opens X :=
  List.foldr (· ⊔ ·) ⊥

@[simp] lemma opensUnion_nil : opensUnion ([] : List (Opens X)) = ⊥ := rfl

@[simp] lemma opensUnion_cons (U : Opens X) (L : List (Opens X)) :
    opensUnion (U :: L) = U ⊔ opensUnion L := rfl

@[simp] lemma inf_opensUnion (U : Opens X) (L : List (Opens X)) :
    U ⊓ opensUnion L = opensUnion (L.map (U ⊓ ·)) := by
  induction L with
  | nil => simp
  | cons V L ih => simp only [opensUnion_cons, List.map_cons, inf_sup_left, ih]

private noncomputable abbrev localHPrime
    (hExt : HasExt.{u + 1} (TopCat.Sheaf AddCommGrpCat.{u} X))
    (F : TopCat.Sheaf AddCommGrpCat.{u} X) (n : ℕ) (U : Opens X) : Type (u + 1) :=
  @Sheaf.H' (Opens X) _ (Opens.grothendieckTopology X) _ hExt F n U

/-- Positive local cohomology vanishes on every nonempty intersection generated by a list.

For `U :: L`, besides acyclicity on `U` and on intersections generated by `L`, the third field
records acyclicity on intersections which also contain `U`. -/
inductive IntersectionAcyclic
    (F : TopCat.Sheaf AddCommGrpCat.{u} X)
    (hExt : HasExt.{u + 1} (TopCat.Sheaf AddCommGrpCat.{u} X)) :
    List (Opens X) → Prop
  | nil : IntersectionAcyclic F hExt []
  | cons (U : Opens X) (L : List (Opens X))
      (head : ∀ (n : ℕ), 0 < n → Subsingleton (localHPrime hExt F n U))
      (tail : IntersectionAcyclic F hExt L)
      (intersections : IntersectionAcyclic F hExt (L.map (U ⊓ ·))) :
      IntersectionAcyclic F hExt (U :: L)

set_option maxHeartbeats 1600000 in
/-- A union of `m` opens with acyclic nonempty intersections has no cohomology in degrees
`n ≥ m`.  This is the finite-cover Mayer--Vietoris bound. -/
theorem HPrime_subsingleton_opensUnion_of_intersectionAcyclic
    (F : TopCat.Sheaf AddCommGrpCat.{u} X)
    [hExt : HasExt.{u + 1} (TopCat.Sheaf AddCommGrpCat.{u} X)]
    {L : List (Opens X)} (hL : IntersectionAcyclic F hExt L)
    (hne : L ≠ []) (n : ℕ) (hn : L.length ≤ n) :
    Subsingleton (localHPrime hExt F n (opensUnion L)) := by
  induction hL generalizing n with
  | nil => exact (hne rfl).elim
  | cons U L hU hL hUL ihL ihUL =>
      have hnCons : L.length + 1 ≤ n := by
        simpa only [List.length_cons] using hn
      by_cases hnil : L = []
      · subst L
        simpa using hU n (by omega)
      · let S := Opens.mayerVietorisSquare U (opensUnion L)
        have hnpos : 0 < n := by
          have : 2 ≤ (U :: L).length := by
            cases L with
            | nil => contradiction
            | cons => simp
          omega
        have hnTail : L.length ≤ n := by omega
        have hnInter : (L.map (U ⊓ ·)).length ≤ n - 1 := by
          simp only [List.length_map]
          omega
        letI : Subsingleton (localHPrime hExt F n U) := hU n hnpos
        letI : Subsingleton (localHPrime hExt F n (opensUnion L)) := ihL hnil n hnTail
        letI : Subsingleton (localHPrime hExt F (n - 1) (U ⊓ opensUnion L)) := by
          rw [inf_opensUnion]
          exact ihUL (by
            cases L with
            | nil => contradiction
            | cons => simp) (n - 1) hnInter
        let seq :=
          @GrothendieckTopology.MayerVietorisSquare.sequence
            (Opens X) _ (Opens.grothendieckTopology X) _ _ hExt
            S F (n - 1) n (by omega)
        have hseq : seq.Exact :=
          @GrothendieckTopology.MayerVietorisSquare.sequence_exact
            (Opens X) _ (Opens.grothendieckTopology X) _ _ hExt
            S F (n - 1) n (by omega)
        have hall (x : localHPrime hExt F n (opensUnion (U :: L))) : x = 0 := by
          change localHPrime hExt F n S.X₄ at x
          let A : AddCommGrpCat.{u + 1} :=
            @Sheaf.H' (Opens X) _ (Opens.grothendieckTopology X) _ hExt F n S.X₂
          let B : AddCommGrpCat.{u + 1} :=
            @Sheaf.H' (Opens X) _ (Opens.grothendieckTopology X) _ hExt F n S.X₃
          have hx : (@GrothendieckTopology.MayerVietorisSquare.toBiprod
              (Opens X) _ (Opens.grothendieckTopology X) _ _ hExt S F n) x = 0 := by
            rw [@GrothendieckTopology.MayerVietorisSquare.toBiprod_apply
              (Opens X) _ (Opens.grothendieckTopology X) _ _ hExt S F n x]
            change (AddCommGrpCat.biprodIsoProd A B).inv _ = 0
            apply (AddCommGrpCat.biprodIsoProd A B).addCommGroupIsoToAddEquiv.injective
            simp only [map_zero]
            ext
            · change (_ : localHPrime hExt F n U) = _
              exact Subsingleton.elim _ _
            · change (_ : localHPrime hExt F n (opensUnion L)) = _
              exact Subsingleton.elim _ _
          obtain ⟨y, hy⟩ := (ShortComplex.ab_exact_iff
            (seq.sc hseq.toIsComplex 2)).mp
              (hseq.exact 2) x hx
          have hy₀ : y = 0 := by
            change localHPrime hExt F (n - 1) (U ⊓ opensUnion L) at y
            exact Subsingleton.elim y 0
          rw [hy₀, map_zero] at hy
          exact hy.symm
        exact ⟨fun x y ↦ (hall x).trans (hall y).symm⟩

end CategoryTheory.Sheaf

namespace AlgebraicGeometry.Cohomology

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace

variable {X : Scheme.{u}}

private lemma image_pi_of_isOpenImmersion {Y Z : Scheme.{u}} (f : Y ⟶ Z)
    [IsOpenImmersion f] {I : Type*} [Fintype I] [Nonempty I] (V : I → Y.Opens) :
    f ''ᵁ (∏ᶜ V) = ∏ᶜ (fun i ↦ f ''ᵁ V i) := by
  apply le_antisymm
  · apply leOfHom
    apply Pi.lift
    intro i
    exact homOfLE (f.image_mono (leOfHom (Pi.π V i)))
  · let i₀ : I := Classical.choice inferInstance
    have hRange : (∏ᶜ fun i ↦ f ''ᵁ V i) ≤ f.opensRange :=
      (leOfHom (Pi.π (fun i ↦ f ''ᵁ V i) i₀)).trans
        (f.image_le_opensRange (V i₀))
    rw [← inf_eq_right.mpr hRange, ← f.image_preimage_eq_opensRange_inf]
    apply f.image_mono
    apply leOfHom
    apply Pi.lift
    intro i
    apply homOfLE
    rw [← f.preimage_image_eq (V i)]
    exact f.preimage_mono (leOfHom (Pi.π (fun i ↦ f ''ᵁ V i) i))

private noncomputable def restrictAppAddCommGrpIso {Y Z : Scheme.{u}} (f : Y ⟶ Z)
    [IsOpenImmersion f] (M : Z.Modules) (V : Y.Opens) (W : Z.Opens)
    (hW : f ''ᵁ V = W) :
    ((Scheme.Modules.toSheaf Y).obj (M.restrict f)).obj.obj (op V) ≅
      ((Scheme.Modules.toSheaf Z).obj M).obj.obj (op W) := by
  subst W
  exact Iso.refl _

set_option maxHeartbeats 1600000 in
private noncomputable def restrictCechComplexIso {Y Z : Scheme.{u}} (f : Y ⟶ Z)
    [IsOpenImmersion f] (M : Z.Modules) {I : Type u} (V : I → Y.Opens) :
    (cechComplexFunctor V).obj ((Scheme.Modules.toSheaf Y).obj (M.restrict f)).obj ≅
      (cechComplexFunctor (fun i ↦ f ''ᵁ V i)).obj
        ((Scheme.Modules.toSheaf Z).obj M).obj := by
  let e :
      (Limits.FormalCoproduct.cosimplicialObjectFunctor
          (Limits.FormalCoproduct.mk I V).cech).obj
          ((Scheme.Modules.toSheaf Y).obj (M.restrict f)).obj ≅
        (Limits.FormalCoproduct.cosimplicialObjectFunctor
          (Limits.FormalCoproduct.mk I (fun i ↦ f ''ᵁ V i)).cech).obj
          ((Scheme.Modules.toSheaf Z).obj M).obj := by
    apply NatIso.ofComponents
    · intro n
      dsimp [Limits.FormalCoproduct.cosimplicialObjectFunctor]
      exact Pi.mapIso fun q ↦ restrictAppAddCommGrpIso f M
        (∏ᶜ fun k ↦ V (q k)) (∏ᶜ fun k ↦ f ''ᵁ V (q k))
        (image_pi_of_isOpenImmersion f _)
    · intro n m g
      apply Limits.Pi.hom_ext
      intro q
      dsimp [Limits.FormalCoproduct.cosimplicialObjectFunctor,
        restrictAppAddCommGrpIso]
  exact (AlgebraicTopology.alternatingCofaceMapComplex AddCommGrpCat).mapIso e

/-- The compact distinguished-open basis lying below one fixed affine open of a scheme. -/
noncomputable def affineBasicOpenBasisAt (U : X.Opens) (hU : IsAffineOpen U) :
    CategoryTheory.Sheaf.CompactOpenBasis X where
  carrier := Set.range (X.basicOpen : Γ(X, U) → X.Opens)
  isCompact := by
    rintro V ⟨f, rfl⟩
    exact (hU.basicOpen f).isCompact
  finite_refinement := by
    rintro V ⟨d, rfl⟩ I W hVW
    let A : Set (X.Opens) :=
      { T | T ∈ Set.range (X.basicOpen : Γ(X, U) → X.Opens) ∧
        T ≤ X.basicOpen d ∧ ∃ i, T ≤ W i }
    have hcover : X.basicOpen d ≤ sSup A := by
      intro x hxd
      have hxW : x ∈ ⨆ i, W i := hVW hxd
      rw [Opens.mem_iSup] at hxW
      obtain ⟨i, hxi⟩ := hxW
      let x' : (W i ⊓ X.basicOpen d : X.Opens) := ⟨x, hxi, hxd⟩
      have hxU : (x' : X) ∈ U := X.basicOpen_le d hxd
      obtain ⟨f, hf, hxf⟩ := hU.exists_basicOpen_le x' hxU
      have hfA : X.basicOpen f ∈ A :=
        ⟨⟨f, rfl⟩, hf.trans inf_le_right, i, hf.trans inf_le_left⟩
      exact (le_sSup hfA) hxf
    obtain ⟨s, hs⟩ := (hU.basicOpen d).isCompact.elim_finite_subcover
      (fun T : A ↦ (T.1 : Set X)) (fun T ↦ T.1.2) (by
        intro x hxd
        have hx : x ∈ sSup A := hcover hxd
        rw [Opens.mem_sSup] at hx
        obtain ⟨T, hTA, hxT⟩ := hx
        exact Set.mem_iUnion.2 ⟨⟨T, hTA⟩, hxT⟩)
    let J := s
    let T : J → X.Opens := fun j ↦ j.1.1
    let a : J → I := fun j ↦ Classical.choose j.1.2.2.2
    refine ⟨J, inferInstance, T, a, fun j ↦ j.1.2.1,
      fun j ↦ Classical.choose_spec j.1.2.2.2, ?_⟩
    apply le_antisymm
    · intro x hxd
      have hx : x ∈ ⋃ j ∈ s, (j.1 : Set X) := hs hxd
      simp only [Set.mem_iUnion] at hx
      obtain ⟨j, hj, hxj⟩ := hx
      rw [Opens.mem_iSup]
      exact ⟨⟨j, hj⟩, hxj⟩
    · rw [iSup_le_iff]
      intro j
      exact j.1.2.2.1
  inf_mem := by
    rintro V W ⟨f, rfl⟩ ⟨g, rfl⟩
    exact ⟨f * g, Scheme.basicOpen_mul X f g⟩

/-- The target affine open belongs to its own distinguished-open basis as `D(1)`. -/
lemma mem_affineBasicOpenBasisAt (U : X.Opens) (hU : IsAffineOpen U) :
    U ∈ (affineBasicOpenBasisAt U hU).carrier :=
  ⟨1, Scheme.basicOpen_one X⟩

/-- Quasi-coherent module sheaves on an affine spectrum are Cech-acyclic on its distinguished
open basis. -/
theorem modulesSpec_isCechAcyclicOnCompactBasis
    {R : CommRingCat.{u}} (G : (Spec R).Modules) [G.IsQuasicoherent] :
    CategoryTheory.Sheaf.IsCechAcyclicOnCompactBasis (affineBasicOpenBasis R)
      ((Scheme.Modules.toSheaf (Spec R)).obj G) := by
  letI : IsIso G.fromTildeΓ :=
    Scheme.Modules.isIso_fromTildeΓ_of_isQuasicoherent G
  let e := (Scheme.Modules.toSheaf (Spec R)).mapIso (asIso G.fromTildeΓ)
  intro I _ V hV W hW hcover n hn
  exact (underlyingTilde_isCechAcyclicOnCompactBasis
    (moduleSpecΓFunctor.obj G) V hV W hW hcover n hn).of_iso
      ((cechComplexFunctor W).mapIso
        ((sheafToPresheaf (Opens.grothendieckTopology (Spec R)) AddCommGrpCat).mapIso e))

set_option maxHeartbeats 1000000 in
/-- The underlying abelian sheaf of a quasi-coherent module is Cech-acyclic on the local
distinguished-open basis below an affine open. -/
theorem modules_isCechAcyclicOn_affineBasicOpenBasisAt
    (G : X.Modules) [G.IsQuasicoherent] (U : X.Opens) (hU : IsAffineOpen U) :
    CategoryTheory.Sheaf.IsCechAcyclicOnCompactBasis (affineBasicOpenBasisAt U hU)
      ((Scheme.Modules.toSheaf X).obj G) := by
  let G' : (Spec Γ(X, U)).Modules := G.restrict hU.fromSpec
  have hG' : CategoryTheory.Sheaf.IsCechAcyclicOnCompactBasis
      (affineBasicOpenBasis Γ(X, U)) ((Scheme.Modules.toSheaf (Spec Γ(X, U))).obj G') :=
    modulesSpec_isCechAcyclicOnCompactBasis G'
  intro I _ V hV W hW hcover n hn
  obtain ⟨d, rfl⟩ := hV
  choose f hf using hW
  have hWeq : W = fun i ↦ X.basicOpen (f i) := funext fun i ↦ (hf i).symm
  subst W
  have hcover' : _root_.PrimeSpectrum.basicOpen d =
      ⨆ i, _root_.PrimeSpectrum.basicOpen (f i) := by
    apply hU.fromSpec.image_injective
    change (hU.fromSpec ''ᵁ _root_.PrimeSpectrum.basicOpen d) =
      hU.fromSpec ''ᵁ (⨆ i, _root_.PrimeSpectrum.basicOpen (f i))
    rw [hU.fromSpec.image_iSup]
    simpa only [hU.fromSpec_image_basicOpen] using hcover
  have h := hG' (_root_.PrimeSpectrum.basicOpen d)
    ⟨d, rfl⟩ (fun i ↦ _root_.PrimeSpectrum.basicOpen (f i))
    (fun i ↦ ⟨f i, rfl⟩) hcover' n hn
  change ((cechComplexFunctor (fun i ↦ _root_.PrimeSpectrum.basicOpen (f i))).obj
    ((Scheme.Modules.toSheaf (Spec Γ(X, U))).obj
      (G.restrict hU.fromSpec)).obj).ExactAt n at h
  have h' := h.of_iso (restrictCechComplexIso hU.fromSpec G
    (fun i ↦ _root_.PrimeSpectrum.basicOpen (f i)))
  simpa only [hU.fromSpec_image_basicOpen] using h'

/-- Positive local cohomology of a quasi-coherent module vanishes on an affine open.  The
cohomology group here is the actual ambient `Sheaf.H'`, not cohomology of an unrelated sheaf on
an abstract affine model. -/
theorem modules_HPrime_subsingleton_of_isAffineOpen
    (G : X.Modules) [G.IsQuasicoherent] (U : X.Opens) (hU : IsAffineOpen U)
    (n : ℕ) (hn : 0 < n)
    [hExt : HasExt.{u + 1} (TopCat.Sheaf AddCommGrpCat.{u} X)] :
    Subsingleton (@Sheaf.H' (Opens X) _ (Opens.grothendieckTopology X) _ hExt
      ((Scheme.Modules.toSheaf X).obj G) n U) :=
  CategoryTheory.Sheaf.HPrime_subsingleton_of_isCechAcyclicOnCompactBasis
    (affineBasicOpenBasisAt U hU) ((Scheme.Modules.toSheaf X).obj G)
    (modules_isCechAcyclicOn_affineBasicOpenBasisAt G U hU) U
    (mem_affineBasicOpenBasisAt U hU) n hn (hExt := hExt)

/-- If every member of a finite list of opens is affine and the diagonal is affine, then a
quasi-coherent module is acyclic on every nonempty intersection generated by the list. -/
theorem modules_intersectionAcyclic_of_forall_isAffineOpen
    (G : X.Modules) [G.IsQuasicoherent]
    [IsAffineHom (pullback.diagonal (terminal.from X))]
    [hExt : HasExt.{u + 1} (TopCat.Sheaf AddCommGrpCat.{u} X)]
    (L : List X.Opens) (hL : ∀ V ∈ L, IsAffineOpen V) :
    @CategoryTheory.Sheaf.IntersectionAcyclic X ((Scheme.Modules.toSheaf X).obj G) hExt L := by
  cases L with
  | nil => exact .nil
  | cons U L =>
      refine .cons U L (fun n hn ↦
        modules_HPrime_subsingleton_of_isAffineOpen G U (hL U (by simp)) n hn
          (hExt := hExt))
        (modules_intersectionAcyclic_of_forall_isAffineOpen G L
          (fun V hV ↦ hL V (by simp [hV])) (hExt := hExt)) ?_
      apply modules_intersectionAcyclic_of_forall_isAffineOpen G (hExt := hExt)
      intro V hV
      obtain ⟨W, hWL, rfl⟩ := List.mem_map.mp hV
      exact IsAffineOpen.inf (hL U (by simp)) (hL W (by simp [hWL]))
termination_by L.length
decreasing_by all_goals simp_all only [List.length_cons, List.length_map]; omega

/-- A fixed nonempty finite affine cover used to state an explicit cohomological bound.  The
empty affine open is prepended so the list remains nonempty even for the empty scheme. -/
noncomputable def finiteAffineCoverOpens (X : Scheme.{u}) [CompactSpace X] : List X.Opens :=
  ⊥ :: Finset.univ.toList.map
    (fun i : X.affineCover.finiteSubcover.I₀ ↦
      (X.affineCover.finiteSubcover.f i).opensRange)

@[simp] lemma finiteAffineCoverOpens_ne_nil (X : Scheme.{u}) [CompactSpace X] :
    finiteAffineCoverOpens X ≠ [] := by
  simp [finiteAffineCoverOpens]

private lemma le_opensUnion_of_mem {L : List X.Opens} {U : X.Opens} (hU : U ∈ L) :
    U ≤ CategoryTheory.Sheaf.opensUnion L := by
  induction L with
  | nil => simp at hU
  | cons V L ih =>
      simp only [List.mem_cons] at hU
      rcases hU with rfl | hU
      · exact le_sup_left
      · exact ih hU |>.trans le_sup_right

/-- The chosen finite list really covers the scheme. -/
lemma opensUnion_finiteAffineCoverOpens (X : Scheme.{u}) [CompactSpace X] :
    CategoryTheory.Sheaf.opensUnion (finiteAffineCoverOpens X) = ⊤ := by
  apply top_unique
  rw [← X.affineCover.finiteSubcover.iSup_opensRange]
  apply iSup_le
  intro i
  apply le_opensUnion_of_mem
  simp [finiteAffineCoverOpens]

/-- Every member of the chosen finite cover is affine. -/
lemma isAffineOpen_of_mem_finiteAffineCoverOpens
    (X : Scheme.{u}) [CompactSpace X] (U : X.Opens)
    (hU : U ∈ finiteAffineCoverOpens X) : IsAffineOpen U := by
  simp only [finiteAffineCoverOpens, List.mem_cons, List.mem_map,
    Finset.mem_toList, Finset.mem_univ, true_and] at hU
  rcases hU with rfl | ⟨i, rfl⟩
  · exact isAffineOpen_bot X
  · exact isAffineOpen_opensRange _

/-- The explicit finite-affine-cover bound. -/
noncomputable def cohomologicalBound (X : Scheme.{u}) [CompactSpace X] : ℕ :=
  (finiteAffineCoverOpens X).length

set_option maxHeartbeats 400000 in
/-- Cohomology of a quasi-coherent module vanishes strictly above the explicit finite affine
cover bound.  Only quasi-compactness and an affine diagonal are used. -/
theorem modules_H_subsingleton_of_cohomologicalBound
    (G : X.Modules) [G.IsQuasicoherent] [CompactSpace X]
    [IsAffineHom (pullback.diagonal (terminal.from X))]
    [hExt : HasExt.{u + 1} (TopCat.Sheaf AddCommGrpCat.{u} X)]
    (n : ℕ) (hn : cohomologicalBound X < n) :
    Subsingleton (@Sheaf.H (Opens X) _ (Opens.grothendieckTopology X)
      ((Scheme.Modules.toSheaf X).obj G) inferInstance hExt n) := by
  let L := finiteAffineCoverOpens X
  have hA : @CategoryTheory.Sheaf.IntersectionAcyclic X
      ((Scheme.Modules.toSheaf X).obj G) hExt L :=
    modules_intersectionAcyclic_of_forall_isAffineOpen G L (hExt := hExt)
      (fun U hU ↦ isAffineOpen_of_mem_finiteAffineCoverOpens X U hU)
  have hH' := CategoryTheory.Sheaf.HPrime_subsingleton_opensUnion_of_intersectionAcyclic
    ((Scheme.Modules.toSheaf X).obj G) hA (finiteAffineCoverOpens_ne_nil X) n (by
      dsimp [cohomologicalBound, L] at hn ⊢
      omega) (hExt := hExt)
  rw [opensUnion_finiteAffineCoverOpens X] at hH'
  exact (@CategoryTheory.Sheaf.subsingleton_HPrime_iff_H (Opens X) _
    (Opens.grothendieckTopology X) _ hExt ⊤ Limits.isTerminalTop _ n).mp hH'

/-- Coherent sheaves inherit the same explicit finite-affine-cover bound. -/
theorem coherent_H_subsingleton_of_cohomologicalBound
    (F : Coh X) [CompactSpace X]
    [IsAffineHom (pullback.diagonal (terminal.from X))]
    (n : ℕ) (hn : cohomologicalBound X < n) :
    Subsingleton ((coherentH X n).obj F) := by
  letI hExt : HasExt.{u + 1} (TopCat.Sheaf AddCommGrpCat.{u} X) := HasExt.standard _
  letI : ((Coh.ι X).obj F).IsFinitePresentation := F.property
  change Subsingleton
    (@Sheaf.H (Opens X) _ (Opens.grothendieckTopology X)
      ((Scheme.Modules.toSheaf X).obj ((Coh.ι X).obj F)) inferInstance hExt n)
  exact modules_H_subsingleton_of_cohomologicalBound ((Coh.ι X).obj F) n hn
    (hExt := hExt)

namespace FiniteDimensionalCohomology

variable {k : Type u} [Field k] {Y : Variety k}

/-- Add the independent finite-affine-cover vanishing theorem to degreewise finite-dimensional
cohomology.  This is the constructor which turns the output of #29 into the `FiniteCohomology`
package consumed by Euler characteristics. -/
noncomputable def toFiniteCohomology (D : FiniteDimensionalCohomology Y)
    [IsNoetherian Y.toScheme]
    [IsAffineHom (pullback.diagonal (terminal.from Y.toScheme))] : FiniteCohomology Y where
  toFiniteDimensionalCohomology := D
  bound := fun _ ↦ cohomologicalBound Y.toScheme
  vanishesAbove := by
    intro F i hi
    have hH : Subsingleton ((coherentH Y.toScheme i).obj F) :=
      coherent_H_subsingleton_of_cohomologicalBound F i hi
    let e := (D.comparison i).app F
    exact ⟨fun x y ↦
      (AddCommGrpCat.mono_iff_injective e.hom).mp inferInstance (hH.elim (e.hom x) (e.hom y))⟩

end FiniteDimensionalCohomology

end AlgebraicGeometry.Cohomology
